feature: dumping stats about each entrypoint and the chunks it uses
django-webpack/webpack-bundle-tracker pull request #41
Opened 2018-11-15 10:31 UTC by alihazemfarouk

This makes it possible for django-webpack-loader or any similar packages to automatically include all assets for a particular endpoint, making it possible to split vendor code into small chunks and ship the least amount possible of code

2018-11-15 16:08 UTC, scdekov requested changes

2018-11-15 16:08 UTC, scdekov commented on index.js
> +          chunkName += renderedHashToAppend;
I'm suspicious about that line. I think adding the hash should not be dependent to the environment, but to the `output` webpack setting. Unfortunately I'll not able to run that code soon, so I can't give you a suggestion how to change that.

2018-11-16 00:01 UTC, scdekov commented on index.js
> +        chunkName += '.js';
Is this always the correct extension?

2018-11-16 16:17 UTC, scdekov commented
Do you think there is a benefit of having that extra level of nesting that can be seen in the last commit? If not I would say to flatten it, IMO it is more simple flattened.

2018-11-16 20:33 UTC, alihazemfarouk commented
I thought it would be better to follow the same format that's already being used in "chunks" key.  Every entryPoint consists of chunks and every chunk consists of (possibly) multiple files

2018-11-17 14:00 UTC, scdekov commented
@alihazemfarouk ok, maybe there is some use case that I'm not familiar with. I think this PR is ready for closing.

2018-11-17 14:00 UTC, scdekov approved these changes

2018-12-03 11:15 UTC, persocon commented
👍

2019-01-21 14:31 UTC, persocon commented
can we merge this please? 🙏

2019-02-14 17:09 UTC, bhrutledge commented
@owais @alihazemfarouk @scdekov 

First, thanks for all of your work to keep this up-to-date with webpack.

I'm considering django-webpack-loader for a project, and encountered the issues around `optimization.splitChunks` as described in https://github.com/owais/django-webpack-loader/issues/157 and https://github.com/owais/django-webpack-loader/issues/165. I though it would be useful to round up all the relevant links here, for folks to review.

This PR and https://github.com/owais/django-webpack-loader/pull/182 seem to offer a viable solution. This PR also seems to take precedence over https://github.com/owais/webpack-bundle-tracker/pull/37.

I installed [django-webpack4-loader](https://pypi.org/project/django-webpack4-loader/) and [webpack4-bundle-tracker](https://www.npmjs.com/package/webpack4-bundle-tracker) (which incorporate the PR's above), and the `render_entrypoint` template tag behaves the way I hoped.

Is there anything blocking the merge of these PR's, and if so, how can we help?

2019-03-15 21:01 UTC, joshgeller commented
Any updates here? How can we help get this merged? Thanks!

2019-03-31 10:41 UTC, arvindamirtaa commented
This would be ideal for my use case. Looks like it's been open for a while. How can we help?

2019-05-01 13:18 UTC, tony commented
@owais This PR is a blocker for `splitChunks` support in webpack v4.  Any thoughts on merging this? It looks like this approach is backwards compatible and would give us the right data in the manifest to render split bundles.

2019-05-01 13:19 UTC, tony commented
@alihazemfarouk Nice job on this and @bhrutledge great job reading through and making sense of this. There's a bit of coordination involved since we need the right data in the manifest file (from webpack-bundle-tracker) to get the rendering we want.

2019-05-01 14:04 UTC, greggb commented
It's pretty clear this package has gone dormant*. Moving on with the fork is probably a good idea for anyone looking to use webpack4. I did this a few weeks ago and it's working well. A few gotchas:
- pip uninstall the python module before re-installing the fork
- Watch the naming conventions closely (`webpack`/`webpack4`) as the docs are not consistently updated with this.

*_Totally understandable for an author to move on - no blame here, and much appreciation for all the work keeping it going so long._

2019-05-01 14:07 UTC, tony commented
> *Totally understandable for an author to move on - no blame here, and much appreciation for all the work keeping it going so long.

I've been reading this issues, where does @owais say he isn't maintaining this anymore?

2019-05-01 14:07 UTC, tony commented
@greggb

> *Totally understandable for an author to move on - no blame here, and much appreciation for all the work keeping it going so long.

I've been reading this issues, where does @owais say he isn't maintaining this anymore?

2019-05-01 14:17 UTC, greggb commented
> I've been reading this issues, where does @owais say he isn't maintaining this anymore?

I'm making this assumption based on activity.

2019-05-01 14:30 UTC, tony commented
@greggb Understood. To avoid derailing this thread, I created a thread at #46 to ask if @owais would like help maintaining the projects (since these are pretty popular packages and there seems to be many willing to help out!).

2020-01-08 13:54 UTC, owais commented
We released 1.0.0-alpha.0 that has webpack 4 support (thanks to @melck). Can someone verify if this is covered by the new alpha release or if something more needs to be done?

2020-01-08 14:42 UTC, tony commented
@alihazemfarouk can you rebase this against master and see if it includes anything extra we want to throw in while we're here?

CC: @owais

2020-10-29 01:43 UTC, andersk commented
This has been superseded by at least one of #53 or #66.

2020-10-29 01:43 UTC, closed without merging